version: '3'
services:
  mall-admin:
    image: mall-admin:1.0-SNAPSHOT
    build:
      context: ./
      dockerfile: Dockerfile-mall-admin
    container_name: mall-admin
    restart: always
    ports:
      - 8080:8080
    volumes:
      - /mydata/app/mall-admin/logs:/var/logs
      - /etc/localtime:/etc/localtime
    environment:
      - 'TZ="Asia/Shanghai"'
    external_links:
      - redis:redis #可以用redis这个域名访问redis服务
      - logstash:logstash #可以用logstash这个域名访问logstash服务
  mall-search:
    image: mall-search:1.0-SNAPSHOT
    build:
      context: ./
      dockerfile: Dockerfile-mall-search
    container_name: mall-search
    restart: always
    ports:
      - 8081:8081
    volumes:
      - /mydata/app/mall-search/logs:/var/logs
      - /etc/localtime:/etc/localtime
    environment:
      - 'TZ="Asia/Shanghai"'
    external_links:
      - elasticsearch:es #可以用es这个域名访问elasticsearch服务
  mall-portal:
    image: mall-portal:1.0-SNAPSHOT
    build:
      context: ./
      dockerfile: Dockerfile-mall-portal
    container_name: mall-portal
    restart: always
    ports:
      - 8085:8085
    volumes:
      - /mydata/app/mall-portal/logs:/var/logs
      - /etc/localtime:/etc/localtime
    environment:
      - 'TZ="Asia/Shanghai"'
    external_links:
      - redis:redis #可以用redis这个域名访问redis服务
      - mongo:mongo #可以用mongo这个域名访问mongo服务
      - rabbitmq:rabbitmq #可以用rabbitmq这个域名访问rabbitmq服务
